name: Update README

on:
  push:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write # <--- THIS GRANTS WRITE PERMISSION FOR PUSHING

    steps:
      - uses: actions/checkout@master

      - uses: "actions-go/go-install@main"
        id: install
        with:
          module: "github.com/hashim-cpro/markscribe@c32e5c9f83470e96ea1af83c48ccd1269a0a089c"

      - name: generate readme
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
          HACKATIME_USERNAME: ${{ secrets.WAKATIME_USERNAME }}
        run: ${{ steps.install.outputs.install-path }} -write README.md templates/README.md.tpl

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe ðŸ¤–
          commit_user_email: actions@github.com
          commit_author: readme-scribe ðŸ¤– <actions@github.com>
